# Default values for 42c-proxy release.

image:
  repository: 42crunch/apifirewall
  # replace with named version in production
  version: latest
  pullPolicy: Always

apifirewall:
  log_level: warn
  # Using this domain + release name as server name
  server_name: photo-demo.westeurope.cloudapp.azure.com
  # existing external IP
  # svc_externalIP: 3.71.18.34
  # Transaction logs can be shipped to the PLATFORM or kept in FILES
  log_destination: FILES
  # Disable listeing with TLS
  http_only: "enabled"
  #The name of the cert API firewall used for TLS configuration (PEM format)
  firewall_tls_cert: tls.crt
  # The name of the private key API firewall used for TLS configuration (PEM format)
  firewall_tls_key: tls.key
  # The port API Firewall pod listens on - Default is 8443 with TLS active
  pod_listen_port: 8080
  # The port API Firewall service listens on - Default is 443 with TLS active
  svc_listen_port: 80
  # Pass the value of Host unchanged
  preserve_host: 'Off'
  # Time to wait for incoming traffic (secs)
  client_timeout: 60
  # Time before a connection to back-end is recycled
  keep_alive_timeout: 60
  # URL for back-end API
  backend_api_url: http://localhost:8090
  
  # Load Balancer Type
  loadBalancerType: LoadBalancer
  # External Traffic Policy - Using local so that original client IP shows up in logs.
  trafficPolicy: Local
  # record request and response bodies to ensure better OAS qualoty in capture
  dump_body: "enabled"
  
  configmap_name: "apifirewall-props"
  # FW token
  protection_token: 80a4aa19-3bee-4bc3-be8d-7da248790a2e
