apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .Release.Name }}-api-tls
  labels:
{{ include "42c-pixiapi.labels" . | indent 4 }}  
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
{{ ( include "api-gen-certs" . ) | indent 2 }}