apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-pixisvc
spec:
  type: {{ .Values.pixiapp.service_type | default "LoadBalancer" }}
  {{ if .Values.pixiapp.svc_externalIP }} 
  loadBalancerIP: {{ .Values.pixiapp.svc_externalIP }} 
  {{end}}
  ports:
  - name: "api"
    port: {{ .Values.pixiapp.svc_listen_port | default 8090 }}
    targetPort: {{ .Values.pixiapp.pod_listen_port | default 8090 }}
  selector:
    app: {{ .Release.Name }}-pixiapp