version: '3'
services:
  pixi-secured.42crunch.test:
    image: 42crunch/apifirewall:latest
    ports:
      - '4241:443'
      - '8880:8880'
    volumes:
      - ./storage/apifirewall/ssl:/opt/guardian/conf/ssl
      - ./storage/apifirewall/logs:/opt/guardian/logs
    command: ["/bin/squire", "-platform", "services.demolabs.42crunch.cloud:8001", "-debug"]
    environment:
      - PROTECTION_TOKEN=${PROTECTION_TOKEN}
      - LISTEN_PORT=443
      - TARGET_URL=https://photo-demo.westeurope.cloudapp.azure.com:443
      - LISTEN_SSL_CERT=full-cert-chain.pem
      - LISTEN_SSL_KEY=key.pem
      - SERVER_NAME=pixi-secured.42crunch.test:4241
      - GUARDIAN_NODE_NAME=Firewall-On-Mac
      - GUARDIAN_INSTANCE_NAME=Demo-Firewall
      - LOG_LEVEL=DEBUG
      - LOG_DESTINATION=PLATFORM
      - BACKEND_TLS_CHECK_PEER_NAME=off
      - BACKEND_TLS_CHECK_PEER_EXPIRE=off
